### ISSUE TITLE
Problem when using RC4, new forms and [(ngModel)]

### ISSUE THREAD

**Issue by geejay** [chymz/ng2-cli-ckeditor-sample#1]
I get this error `platform-browser.umd.js:1900 ORIGINAL EXCEPTION: No value accessor for ''`

when using

`<ckeditor formControlName="notesText" [(ngModel)]="estimate.notes.notesText" (change)="onEditorChanged($event)" [config]="ckEditorConfig" ></ckeditor>`

**Comment by chymz** [comment]
Did you enable old api and enable the new one ?

https://github.com/chymz/ng2-cli-ckeditor-sample/blob/master/src/main.ts#L11

**Comment by geejay** [comment]
Disabling the old API worked - 

Before I had 
`bootstrap(AppComponent, [provideForms()])`

This works as expected:
`bootstrap(AppComponent, [disableDeprecatedForms(),    provideForms()])`

THANKS
